Document: amxa-ap-autostart
Title: Debian amxa-ap-autostart Manual
Author: <insert document author here>
Abstract: This manual describes what amxa-ap-autostart is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/amxa-ap-autostart/amxa-ap-autostart.sgml.gz

Format: postscript
Files: /usr/share/doc/amxa-ap-autostart/amxa-ap-autostart.ps.gz

Format: text
Files: /usr/share/doc/amxa-ap-autostart/amxa-ap-autostart.text.gz

Format: HTML
Index: /usr/share/doc/amxa-ap-autostart/html/index.html
Files: /usr/share/doc/amxa-ap-autostart/html/*.html
